version: '3.9'
services:
  db:
    image: postgres
    restart: always
    container_name: db_uni
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: datatest
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
 
    command: postgres -c max_connections=200 -c shared_buffers=256MB -c logging_collector=on -c log_statement=all

  redis:
    image: redis
    container_name: meu-redis
    ports:
      - "6379:6379"

